apiVersion: v1
kind: Service
metadata:
  name: orderapp-service
spec:
  selector:
    app: orderapp
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 9000
      nodePort: 31110