apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderapp-deployment
  labels:
    app: orderapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderapp
  template:
    metadata:
      labels:
        app: orderapp
    spec:
      containers:
      - name: nodeserver
        image: danish2708/orderapp:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 9000